# Generated by Django 4.0.7 on 2022-09-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_follower_set_user_following_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('naver', 'Naver'), ('kakao', 'Kakao')], default='email', max_length=6),
        ),
    ]
